### ISSUE TITLE
Write comments and have discussion about Notebook contents

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#1]
## Problem
[Visual diff](https://uploads-ssl.webflow.com/5ba4ebe021cb91ae35dbf88c/5ba93ded243329a486dab26e_sl-code%2Bimage.png) is great. But when a user looks at it, the next logical step is to provide some feedback or ask clarifying questions to author. These could be higher level questions about approach/algorithm or more specific questions about code/output.

This is currently done via chat tool (slack etc.) which doesn't have the Notebook context (_which cell are you talking about_). Or it's done on the call or face to face with the Notebook open in the front. That way it becomes a synchronous process (requires scheduling a meeting) and discussion isn't captured anywhere.

## Proposal to Solve
Ability to comment can very well integrate into ReviewNb visual diffs. Take a look at the picture below.

![screenshot 2018-10-23 at 5 35 51 pm](https://user-images.githubusercontent.com/1350490/47359408-4d28a200-d6ea-11e8-8492-53af8c951842.png)

## Benefits
* Comments have the context of Notebook cells to which they apply
* Collaboration workflow becomes asynchronous as opposed to meetings/calls etc.
* The discussion is captured and can be used for reference in future.

_Feel free to upvote/downvote the issue indicating whether you think this is useful feature or not. I also welcome additional questions/comments/discussion on the issue._

**Comment by mirestrepo** [comment]
We'd love to use this feature in a classroom setting as a way to provide feedback to students.

**Comment by amit1rrr** [comment]
Just want to give a quick heads up to everyone interested in the Notebook commenting feature, this is something I'm working on currently. Expect the feature to be released in the next few weeks :)

**Comment by sebinsua** [comment]
Fantastic!

Will this use GitHub's current commenting system and just render the comments into the correct parts of the Notebook?

**Comment by amit1rrr** [comment]
> Will this use GitHub's current commenting system and just render the comments into the correct parts of the Notebook?

It's little better than that.

Yes, all your comments will be posted and stored at GitHub. But you will be able to create comments from the diff view of ReviewNB itself. It would be easier to write comments next to rendered notebook cells.

GitHub has a limitation that you can write comments only on the changed parts of the file. I thought it's too limiting for our use case. I have actually worked around that limitation so people can write comments on any part of the Notebook in a give PR. I'm so excited to share it with y'll. Stay tuned!

**Comment by dshean** [comment]
Hi @amit1rrr.  Currently grading assignments that the students modified in their Github Classroom repos.  The ReviewNB diff functionality is great for notebooks.  Wondering if you have an update on timing of the contextual comments/feedback feature?  My current workaround for line-specific comments through a pull request on the student repo is pretty clunky, especially for notebooks.

**Comment by amit1rrr** [comment]
I'm super excited to tell you that the commenting is now live on [ReviewNB](https://www.reviewnb.com/).

Here's a quick blog post to see all commenting features in action along with screenshots: https://medium.com/@amitrathi/how-to-review-jupyter-notebook-changes-47a8b53dca63

Look forward to your feedback. You can post it here or write to me at hello@amirathi.com

cc: @dshean @sebinsua @mirestrepo

**Comment by sgugger** [comment]
This is exactly what I was looking for as a maintainer of a repo with a lot of notebooks, thank you so much! A little feature request that goes with it, if it's feasible, would be to see the comments left when we go back to the Changes tab (like in regular GitHub when you leave comments).

**Comment by amit1rrr** [comment]
@sgugger Thanks for the feature request. I considered it briefly while building the commenting feature and decided against it mainly because:

- As notebook author pushes more commits to a PR, comments keep rolling in at different commits. E.g. Author creates PR, reviewer leaves 3 comments. Author fixes 2 issues and pushes a commit. Reviewer starts a new discussion on newly posted commit and so on.  
- In this scenario, to be able to see all comments on the diff UI, user can't just stay on the latest PR diff but has to click around _diffs at different commit points_ to see comments written when those commits were latest.

This way the comments on the diff UI are not very accessible. It also makes the while PR experience little more complex than it needs to be. 

Being said that, do you have a strong need to see comments on the diff UI? Is the cell context presented on the discussion tab not enough for the context of the comment?

**Comment by amit1rrr** [comment]
Resolving this since the commenting is now live!

**Comment by richdevboston** [comment]
I appreciate your hard work in creating this concept.  Good idea and better than nbdiff at the moment.  However, I cannot use it within my company now, because it requires a github marketplace license and a monthly fee.     

The current GitHub marketplace fees... 
Lite $15 per month
For moderate notebook usage
Free Trial
Up to 3 Private Repositories, Unlimited Public Repositories, Unlimited Users

And second, we cannot use it if it is hosted on GitHub, because it exposes company proprietary data with the free version.  TOTALLY UNACCEPTABLE !!   It must be free (zero cost) and open source (FOSS) code, and locally installable within my company (for the entire thing) or we cannot use it. 

Can someone else please create something nearly equivalent or more functional and make it FOSS code posted without license or royalties required?   

It must install on local computers and on our internal Jupyter Notebook servers without paying monthly fees or royalties.
