### ISSUE TITLE
Minor rendering problem with inline latexmath in markdown cell 

### ISSUE THREAD

**Issue by bbengfort** [ReviewNB/support#10]
We encountered a minor issue with a markdown cell on the notebook diff page that seems to be occurring because of an inline latexmath block; namely there is a stray `</span>` tag that is being rendered in the diff:

![screenshot 2019-02-19 11 36 20](https://user-images.githubusercontent.com/745966/53031523-00a46780-343b-11e9-88ce-3c758c2f3173.png)

Note that this problem is not occurring when rendering the notebook outside of diff, as in when reviewing the comments/discussion page:

![screenshot 2019-02-19 11 35 37](https://user-images.githubusercontent.com/745966/53031570-1ca80900-343b-11e9-9bfb-37dc122ba019.png)

Or in the original notebook itself (just for verification):

![screenshot 2019-02-19 11 36 52](https://user-images.githubusercontent.com/745966/53031597-27629e00-343b-11e9-9c2e-50ad7f9d4ad0.png)

It appears that the text highlight span is probably also not working, so perhaps the closing span is getting captured in a `<code>` or `<pre>` block? 

Also just want to say thank you so much for this project; doing code reviews on notebooks is definitely a pain and this tool is invaluable!

**Comment by amit1rrr** [comment]
@bbengfort Thank you for reporting the issue. Can you please point me to a commit/PR where this is happening? 

If it's a private repo & you are OK with me taking a look for debugging purposes then just send me the commit/PR URL at [amit@reviewnb.com](mailto:amit@reviewnb.com). Else if you can just reproduce this issue in any of your open source repo, by copying the contents/edits of this commit that would be great. 

> doing code reviews on notebooks is definitely a pain and this tool is invaluable!

Thanks! Glad you like it :)

**Comment by amit1rrr** [comment]
This issue is now fixed. There was a formatting error when there are multiple math formulas interspersed with span tags (green/pink highlighting for diff).

@bbengfort thank you for reporting and help in reproducing the issue.

![screenshot 2019-03-07 at 11 24 33 pm](https://user-images.githubusercontent.com/1350490/53978413-2915ac80-4131-11e9-8044-f7924ac9e380.png)
