### ISSUE TITLE
Could we have right-aligned cell format for the output of pandas dataframe as is applied by other platforms like Github?

### ISSUE THREAD

**Issue by shanshantu** [ReviewNB/support#100]
Noticed that the output of pandas dataframe right now is left-aligned, while it seems more common to have right-aligned formatting.

**Comment by amit1rrr** [comment]
@shanshantu Thank you for reporting this. We've deployed a fix that shows the correct alignment for pandas dataframes. 

Here's an example screenshot after the fix -

![Screenshot 2021-09-10 at 5 53 07 PM](https://user-images.githubusercontent.com/1350490/132852673-2d9f319c-78ac-4016-8acf-a311fa666388.png)
