### ISSUE TITLE
Outage?

### ISSUE THREAD

**Issue by mmaclow** [ReviewNB/support#103]
I am trying to log in at app.reviewnb.com, but am just getting a white screen and loading indicator for many minutes now.  I am using an up to date Chrome Browser on Mac Catalina.

**Comment by amit1rrr** [comment]
@mmaclow We're not seeing any issue in loading the homepage. Can you please try logging out & logging again? (Logout link - [https://app.reviewnb.com/logout](https://app.reviewnb.com/logout))

**Comment by mmaclow** [comment]
Thanks for the quick response!  Unfortunately, your suggestion did not help. I'm still stuck on login with a white screen.  However, since there's no issue at your end, I tried switching to Safari, which did give me full access.  As my primary browser is Chrome, I'd prefer to fix the problem, but this reduces the urgency very substantially.

**Comment by amit1rrr** [comment]
For Chrome -

1. What happens if you try to open the page in a new incognito window? What is the login flow do you see?

2. Can you please check Chrome console for any errors? Also please check Network tab in the Chrome console when the spinner keeps spinning. We'd like to see if there's any network call that's getting stuck.

3. Do you use any Chrome extensions that might be interfering? For sanity check, can you disable all Chrome extensions and try loading the page.

**Comment by mmaclow** [comment]
On Jan 19, 2022, at 2:55 PM, Amit Rathi ***@***.******@***.***>> wrote:

EXTERNAL SENDER



For Chrome -

  1.  What happens if you try to open the page in a new incognito window? What is the login flow do you see?


Ah-ha!  I get taken to GitHub login, and from there to my repo list.  Expected behavior.

2. Can you please check Chrome console for any errors? Also please check Network tab in the Chrome console when the spinner keeps spinning. We'd like to see if there's any network call that's getting stuck.

No errors.  One issue is identified:


  1.

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.

To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.

Note that for performance reasons, only the first access to one of the properties is shown.

  2.  AFFECTED RESOURCES
     *
1 source
        *
MathJax.js:1
  3.
     *
Learn more: User-Agent String Reduction


  1.
  2.  Do you use any Chrome extensions that might be interfering? For sanity check, can you disable all Chrome extensions and try loading the page.


I tried but didn’t get any change in behavior.

  1.

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FReviewNB%2Fsupport%2Fissues%2F103%23issuecomment-1016817017&data=04%7C01%7C%7Ccb6a9db55b7b4138b84408d9db85a9a2%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782189421151282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HuwfaPxSxipGndZiGww%2BUBTiAyoyi%2Fu6ohha%2BzViGI4%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABJTUOFNNK7F5PQYJ5IINYDUW4JLRANCNFSM5MKUBQQQ&data=04%7C01%7C%7Ccb6a9db55b7b4138b84408d9db85a9a2%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782189421151282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D8h8WvVvs97NIjWFIf0ycE7GKLyHWV7KYA17%2FP6SqKI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ccb6a9db55b7b4138b84408d9db85a9a2%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782189421151282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hmnZojcN4g%2FXoTVA2CGRlmkwmKDYOkaxHKBGp9Db%2BzI%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ccb6a9db55b7b4138b84408d9db85a9a2%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782189421307476%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YrOC0cWeBoSYE48efAKDQwTofeu4OQ6sQdCYViVDtwk%3D&reserved=0>.

**Comment by amit1rrr** [comment]
> A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.

This just a warning from Chrome. Likely not related to our issue.


> Ah-ha!  I get taken to GitHub login, and from there to my repo list.  Expected behavior.

Given that the app is working fine in the Chrome incognito mode, I am inclined to say that there's _something_ (extension, locally cached data etc.) in the current state of the browser that's messing things up. Can you please try clearing any local data, browser history etc and try again? Also - do share the version of Chrome that you're facing this with.

**Comment by mmaclow** [comment]
Bingo!  I cleared "Cached images and files” and recovered normal behavior.  If I were going to guess, I’d think that the site got interrupted in the middle of loading, and the interrupted state got cached.  At any rate, the problem has been fixed (this was on Chrome Version 97.0.4692.71 (Official Build) (x86_64)).

Thanks for your effective help with this!

Yours,

Mordecai-Mark Mac Low



On Jan 20, 2022, at 4:22 AM, Amit Rathi ***@***.******@***.***>> wrote:

EXTERNAL SENDER



A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.

This just a warning from Chrome. Likely not related to our issue.

Ah-ha! I get taken to GitHub login, and from there to my repo list. Expected behavior.

Given that the app is working fine in the Chrome incognito mode, I am inclined to say that there's something (extension, locally cached data etc.) in the current state of the browser that's messing things up. Can you please try clearing any local data, browser history etc and try again? Also - do share the version of Chrome that you're facing this with.

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FReviewNB%2Fsupport%2Fissues%2F103%23issuecomment-1017271921&data=04%7C01%7C%7C84c66141d81c4613129b08d9dbf66557%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782673580241612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ewb1hi5y8mKAnpKbXYHWZl%2BKx%2FmgT5QPa%2BezV6nxHkE%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABJTUOH3OE6VATL6IR6OZQTUW7H5XANCNFSM5MKUBQQQ&data=04%7C01%7C%7C84c66141d81c4613129b08d9dbf66557%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782673580241612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yRYWOdgcqmpnRA9CNNN7DCGee6U92XHjFsYA6Kzbz5A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C84c66141d81c4613129b08d9dbf66557%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782673580241612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MwXX6qKoNKh3ApDTtpBYOVpfrW2dbl1R6vDirKHB5eY%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C84c66141d81c4613129b08d9dbf66557%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637782673580241612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9ome08SbgOMuUaZvmopOGpnekaGcd6LGC9DcDJh7vBc%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



--
Mordecai-Mark Mac Low (he/him)  Curator-in-Charge & Professor
+1-212-496-3443          Department of Astrophysics
+1-212-769-5007 (fax)    American Museum of Natural History
mmaclow (Skype, Hangout)     79th St at CPW, NY, NY, 10024-5192, USA

**Comment by amit1rrr** [comment]
Glad the issue is resolved :)
