### ISSUE TITLE
Buggy behavior when inserting code in pull request discussion text block

### ISSUE THREAD

**Issue by mmaclow** [ReviewNB/support#105]
If I'm editing text in a pull request discussion text box and insert a new piece of code in the middle of the text using  backquotes like `x = 1` ([backquote] x = 1 [backquote]), after I enter the final backquote and hit space, the font transforms to code font... but the cursor jumps down to the end of the text, rather than remaining in place after the inserted code block.  It's minor, but rather annoying when I'm doing a whole class worth of discussions.

**Comment by amit1rrr** [comment]
@mmaclow Thank you for reporting this. We've deployed a fix which keeps the cursor position in place even when formatting in the middle of the comment text. 

Resolving. Please feel free to reopen if you see any issues. Thank you again for taking the time in reporting this, appreciate it!
