### ISSUE TITLE
Render attached images in preview

### ISSUE THREAD

**Issue by alanhdu** [ReviewNB/support#106]
In Jupyterlab, you can copy-paste images into a Jupyter notebook that get stored as "attachments" (as in the following GIF):

![index](https://user-images.githubusercontent.com/1914111/164320307-a1b44aad-3a5c-49e9-a8db-b21f4968eb00.gif)

In the notebook, this is stored as an additional `attachments` field in the cell type, like:
```
{
   "cell_type": ...,
   "attachments": {
       {"db08b428-8cc7-4f27-9495-a9ffab5aa30c.png": {"image/png": "base64 string"}}
   },
}
```

This is a super convenient way to ensure that images are bundled with the notebook, but it doesn't look these attached images get rendered on ReviewNB right now (in ReviewNB, I only see the image name getting rendered as text rather than the actual image). Would it be possible to ensure that the actual image is rendered as well?

(I could've sworn this used to work, so it might be that I'm doing something wrong now?)

**Comment by amit1rrr** [comment]
@alanhdu Thank you for reporting this with the detailed information. We've now deployed a fix that renders the attachments properly. Let me know if you face any issues. Thanks again.

Closing. Please feel free to reopen if you see any issues.

**Comment by alanhdu** [comment]
Thanks! I can confirm that this is fixed on our side!
