### ISSUE TITLE
Sync conversation status (Resolved | Unresolved) between ReviewNB & GitHub

### ISSUE THREAD

**Issue by arunpatro-meesho** [ReviewNB/support#107]
When I resolve a comment on review-nb, it doesn't resolve it github. This is a blocker for our development. Please help.

**Comment by amit1rrr** [comment]
GitHub currently does not have an API to resolve / unresolve conversations. Hence we are not able to sync the conversation status on GitHub.


We've an API request open with GitHub, when that API becomes available in GitHub, we'll definitely update conversation status on GitHub. Until then, we request you to simply use ReviewNB UI to track conversations. Apologies for the inconvenience.

**Comment by amit1rrr** [comment]
The issue is being tracked here - https://github.com/ReviewNB/support/issues/124
