### ISSUE TITLE
No response to problem reported by email to support

### ISSUE THREAD

**Issue by shashi-ggd** [ReviewNB/support#108]
Hi, We have a subscription. We are unable to open some of our notebooks for code review. We have reported the problem to support@reviewnb.com 4 days ago, but we have not received even an acknowledgment. Request the support team to respond soon. Thanks.

**Comment by amit1rrr** [comment]
@shashi-ggd Sorry about that. Your email (both to team@ & support@) went into the spam box for some reason. Regardless, I apologise for the poor experience.

We're looking at it now & will respond to you as soon as possible. 


![Screenshot 2022-05-25 at 10 37 19 AM](https://user-images.githubusercontent.com/1350490/170192337-ca63d0ea-dd7f-4344-8881-8bfc88c18117.png)

**Comment by amit1rrr** [comment]
There was indeed a performance issue in some cases when multiple images were present in notebook markdown. 

We've deployed a fix that fixes the performance & the page should render fine. 

Closing. Please feel free to reopen if you're still facing the issue.

**Comment by shashi-ggd** [comment]
We find the issue is resolved and we are able to open the notebooks as expected. Thanks.
