### ISSUE TITLE
[Feature Request] Support suggestions

### ISSUE THREAD

**Issue by muellerzr** [ReviewNB/support#109]
One of the big blockers towards adopting nbdev in companies through Github is the inability to provide and accept reviewer changes on notebooks. 

If this could be implemented, many companies would feel more at ease reviewing them, and systems such as nbdev can get more widespread use.

**Comment by amit1rrr** [comment]
Hello @muellerzr 
Thank you for the feature request.

By `suggestions` you mean, GitHub like workflow where reviewer can suggest a change that the PR author can accept / reject with a single click. Is my understanding correct?

You mentioned nbdev a couple of times, how is that related to this feature request? Am I missing something here?

**Comment by muellerzr** [comment]
Correct, exactly that!

[nbdev](https://nbdev.fast.ai) is an entire literate programming framework revolving around using jupyter notebooks to build software libraries. Having this be a functionality in reviewnb reduces the differences/losses between reviewing a notebook and reviewing raw source code helping bridge more of this gap in Github. 

I *believe* this can be bootstrapped into the github API in some form (I've looked at it quite a bit thanks to [GhApi](https://ghapi.fast.ai)), was debating on toying with it though to just see how that would end up looking. 

(Might be something like ReviewNB makes the actual push to the repo and commits that code)

**Comment by muellerzr** [comment]
Some other useful nbdev-related libs they have include:

- [execnb](https://github.com/fastai/execnb)
- [nbprocess](https://github.com/fastai/nbprocess) (which will be come nbdev v2)

**Comment by amit1rrr** [comment]
Got it, thanks!

I agree that this would be a good addition to ReviewNB. As I mentioned on [this issue](https://github.com/ReviewNB/support/issues/101) the primary blocker is that we do not ask for `write` permission on the repository. So we're not able to push any commits to the repository. 

The alternative here is to comment on a particular line and write suggested changes in the comment. Reviewer can then copy-paste this suggestion. While this is not ideal, it's not too cumbersome either.

**Comment by muellerzr** [comment]
@amit1rrr if we can get that far we can bootstrap our own stuff in nbdev to take it to that last stage 😄 

That'd be amazing!
