### ISSUE TITLE
Dropdown filter on PR List

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#11]
### Assumption
Users most often want to access Open PRs. Merged/Closed PRs are generally not that important.

### Current State
Currently we show list of PRs from latest to oldest. Merged PRs are shown with reduced opacity but they end up taking space and user has to scroll through the list to find the Open PR that they are interested in.

<img width="795" alt="screenshot 2019-03-08 at 3 26 11 pm" src="https://user-images.githubusercontent.com/1350490/54021604-8869d000-41b6-11e9-9a0c-a813c81e492f.png">

### Proposal
Only show Open PRs by default. Have a filter at the top to toggle between All/Open/Merged/Closed PRs.

**Comment by amit1rrr** [comment]
PR list filter is now live.

![Screenshot 2019-03-19 at 11 41 32 PM](https://user-images.githubusercontent.com/1350490/54630764-9665fd80-4aa0-11e9-91b0-2880ee54d2b6.png)

**Comment by ChenQuan** [comment]
> PR列表过滤器现已上线。
> 
> ![截屏2019-03-19 at 11 41 32 PM](https://user-images.githubusercontent.com/1350490/54630764-9665fd80-4aa0-11e9-91b0-2880ee54d2b6.png)

But I did't find it.
![image](https://user-images.githubusercontent.com/20548053/54651488-1070a380-4aee-11e9-9633-cf00abe51399.png)

**Comment by amit1rrr** [comment]
@ChenQuan You need to do a hard refresh (Cmd + R on mac) to fetch updates. Else they appear when you close/reopen the tab or logout/login. 

Let me know if you still didn't see the PR filter.

**Comment by ChenQuan** [comment]
> @ChenQuan You need to do a hard refresh (Cmd + R on mac) to fetch updates. Else they appear when you close/reopen the tab or logout/login.
> 
> Let me know if you still didn't see the PR filter.
@amit1rrr 
Sorry, I have already tried.But I didn't see the PR filter.

**Comment by amit1rrr** [comment]
Ah just saw you only have 8 Pull Requests in the list. 

For less than 10 PRs, we don't show any filters since the list is small enough to be clearly visible in a single glance. Hope that makes sense :)

**Comment by ChenQuan** [comment]
> Ah just saw you only have 8 Pull Requests in the list.
> 
> For less than 10 PRs, we don't show any filters since the list is small enough to be clearly visible in a single glance. Hope that makes sense :)

ok,thanks.
