### ISSUE TITLE
PR base branch not updated

### ISSUE THREAD

**Issue by joeyDIGs** [ReviewNB/support#123]
Hello,

I am reviewing a PR of a feature branch, let's call it `FB1`, against our `main` branch.

The issue is that a second feature branch, let's call it `FB2` was merged into `main` after the aforementioned PR was opened, and I believe there's a bug in reviewNB, as the diff shown does not consider the merged changes of `FB2`

In the below image, you can see more detail, where `FB1` would be the <span style="color:purple">purple  branch</span> and `FB2` would be the <span style="color:blue">blue  branch</span>.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/108298524/221391926-7f4d64c7-8393-4606-a30f-2d2330ec5248.png">

# The Bug

The reviewNB diff is happening between `FB1`'s head and the `main` commit from Feb 1 (red arrow), where it **should** be against `main`'s head (green arrow)

<img width="635" alt="image" src="https://user-images.githubusercontent.com/108298524/221391940-df4257d9-f1b2-4ef6-9edb-ab69217a0cd8.png">

**Comment by amit1rrr** [comment]
@joeyDIGs Thanks for opening the issue with all the details.

ReviewNB's PR diff is based on GitHub PR Diff. So as long as GitHub PR diff is between the latest `main` & `FB1`, we should also be showing the same diff.

Can you please check the GitHub PR & see what diff it is showing? Is ReviewNB showing different diff than what is available on GitHub?

**Comment by amit1rrr** [comment]
Also - please make sure you refresh the ReviewNB PR page or just open it in a new browser tab.

**Comment by amit1rrr** [comment]
Closing this ticket since we haven't heard from you in a while.

@joeyDIGs Please feel free to reopen if the ReviewNB PR diff was showing a different diff than the GitHub PR diff at any point in time.
