### ISSUE TITLE
ReviewNB

### ISSUE THREAD

**Issue by PraneshPrini** [ReviewNB/support#127]
Any video available for ReviewNB for better undestanding

**Comment by amit1rrr** [comment]
Sorry, we don't have any video tutorials. But here's a good [getting started guide](https://levelup.gitconnected.com/a-painless-jupyter-notebook-code-review-and-diff-51d36d8cd20b).

**Comment by PraneshPrini** [comment]
If I go with self hosted with basic plan, what is the requirement and
installation process, mainapur we host it on our own.
