### ISSUE TITLE
No documentation on how to update users on team plan after a user leaves the org

### ISSUE THREAD

**Issue by Smarker** [ReviewNB/support#129]
How can we update user access on our team plan? We keep seeing "plan limit exceeded" even after making sure our reviewNB only is attached to repos with a total of < 10 users. This should be sufficient for all of our < 10 users to access reviewNB, but right now they can't.

**Comment by amit1rrr** [comment]
@Smarker Just replied to your email about the same support request. Let's continue this ticket on the email thread.
