### ISSUE TITLE
reviewnb 

### ISSUE THREAD

**Issue by 0Swathi** [ReviewNB/support#130]
reviewnb was not showing in oullrequesrt

**Comment by amit1rrr** [comment]
@0Swathi Couple of conditions need to be satisfied for ReviewNB link to be shown in the PR 

- The PR is created AFTER the ReviewNB app is installed on the repository
- The PR should have at least 1 notebook file

If the above conditions are satisfied & you still don't see the ReviewNB link on the PR then please share the PR link with us & we'll investigate this.

**Comment by amit1rrr** [comment]
Closing due to lack of response / information. Feel free to re-open if there are any issues or questions.
