### ISSUE TITLE
Can we add an Azure DevOps repository to ReviewNB?

### ISSUE THREAD

**Issue by Sathishbabu-Shanmugam** [ReviewNB/support#132]
Dear Team,

Is it possible to add an Azure DevOps repository to a self-hosted ReviewNB?

If yes, please let me know the process.

Thank you.!

**Comment by amit1rrr** [comment]
Hello @Sathishbabu-Shanmugam 

No, we do not support Azure DevOps at the moment. Please consider moving the repository over to GitHub Cloud or GitHub Enterprise Server for it to work with self-hosted ReviewNB.

Closing. Please feel free to re-open (or email us) for any follow up questions.
