### ISSUE TITLE
Line level comments

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#17]
We currently only support cell level comments. It would be nice to have an ability to comment on specific line in the diff.

The current workaround for users is to copy the line they want to comment on, paste it into the comment section and write the actual comment below it. Not an optimum experience.

***
_Feel free to upvote/downvote the issue indicating whether you think this is useful feature or not. I also welcome additional questions/comments/discussion on the issue._

**Comment by alimanfoo** [comment]
Just to add that this would be a hugely useful feature, sometimes code cells can be long and complex and so ability to comment on specific lines would be very helpful, particularly when you comment on multiple lines within the same cell.

**Comment by c3rajkaramchedu** [comment]
Yes, this feature would be hugely useful. Echoing @alimanfoo.

**Comment by withsmilo** [comment]
@amit1rrr Any update on this issue?

**Comment by amit1rrr** [comment]
@withsmilo No updates at the moment. Line level comments is still on our radar & is one of the high priority feature. I will keep you posted on any updates on this front.

**Comment by perjlieb** [comment]
@amit1rrr this feature would be very helpful. We are currently using one of these two workarounds
- copy and paste the line we want to comment on, as you mentioned
- view diffs on RevievNB but comment on specific lines on the plain Github diff

**Comment by jatkinson-CRL** [comment]
Just wanted to echo everyone else here, this feature would be a gamechanger for this tool. Can't wait to see it implemented!

**Comment by amit1rrr** [comment]
Happy to let everyone know that we've just deployed line level commenting to ReviewNB pull requests. Now you can comment on a specific line in a code cell. Let us know if there's any feedback!

**Comment by coopr** [comment]
Huge upgrade, this is fantastic, thanks so much!!
