### ISSUE TITLE
Instantly play with Notebooks shared by anyone

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#2]
## Problem
There's a lot of content available in the form of Notebooks. But it's not always easy to just download a Notebook and start playing with it. You need to have the right environment (dependent packages, python version, env variables, data files etc.) to be able to execute Notebook code cells.

In the Jupyter world it's called the reproducibility problem i.e. one cannot reproduce the Notebook results given just the Notebook.

## Solution
We'll ask Notebook authors to provide a `dockerfile` in their repo. It's the easiest and most powerful format to specify the complete environment required for Notebook execution. 

Once the Dockerfile is available here's how the workflow will look for users:
* User can browse any GitHub repository containing Notebooks
* There's a tag/url in the Readme file saying "Launch via ReviewNb" (similar to travis build status)
* User clicks on the tag and a new Jupyter environment with all the Notebooks (in the repo) preloaded is available for user to play with.
* User can keep the Jupyter environment, share it with others or kill at the end of the session.

## Benefits
* Solves reproducibility problem of Notebooks
* Users more likely to actually get their handy dirty with the algorithms and data instead of just skimming over the Notebook HTML (learning by practice)
* People can share not just dependencies but even required data files and such via Dockerfile.

_Feel free to upvote/downvote the issue indicating whether you think this is useful feature or not. I also welcome additional questions/comments/discussion on the issue._

**Comment by gnestor** [comment]
The binder project was created to solve this very problem: https://github.com/jupyterhub/binderhub

**Comment by NawfalTachfine** [comment]
I highly recommend using [pipenv](http://pipenv.readthedocs.io/) for this. It's lighter than spawning entire containers for everything.

**Comment by amit1rrr** [comment]
I have been thinking about docker vs. pipenv to power this feature and there are some limitations/oddities with pipenv like below:

- Limits us to only work with Python Jupyter Notebooks. Jupyter itself supports a lot of kernels and would be good for us to be language agnostic & allow 1-click launch for any Jupyter Notebook.
- If running anything require specific low level libraries or OS then that can't be captured in pipenv (very easily codified in Dockerfile)
- Pipenv is good to manage dependencies locally. But I haven't seen users commiting their pipfile or pipfile.lock to the repo. In contrast, commiting Dockerfile to repo is very natural workflow for many.

> It's lighter than spawning entire containers for everything.
I agree with the sentiment that Docker containers/images might feel heavyweight for the use case. That's why we should abstract away all the 'heavy-ness' from the user. They need to only care about having the Dockerfile in the the repo (see my earlier [comment](https://github.com/ReviewNB/support/issues/2#issuecomment-434228949) about making Dockerfile generation semi-automated). The user shouldn't need to know, how/when we create images, how containers are spawned/destroyed etc. Binder is pretty good at abstracting all that away from the users and we should aspire to do the same.

**Comment by NawfalTachfine** [comment]
I think I was too quick to jumpy the trigger. I mainly meant to bring pipenv to your attention. In my own workflow, I actually use both. As you said pip has its limitations and it's more practical to have a base image and be able to tinker with python libs as you experiment without rebuilding your image so often.

Custom kernels are a neat feature but I doubt that they are used much today, save perhaps for R. Have you seen adoption rise for more exotic kernels?

**Comment by amit1rrr** [comment]
> Custom kernels are a neat feature but I doubt that they are used much today, save perhaps for R. Have you seen adoption rise for more exotic kernels?

Not that much really. Mainly Python & R.

**Comment by amit1rrr** [comment]
Closing in favour of #16
