### ISSUE TITLE
Fallback to simple before-after view for complex diffs

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#21]
In rare cases, ReviewNB is unable to compute diff when there are large number of extremely big changes to the file. With large git patch like [this](https://patch-diff.githubusercontent.com/raw/scoutbeedev/pytorch-nlp-notebooks/pull/5.patch) it's hard to accurately build the change events (insert/delete/modify).

Typically this happens in a very small number of cases (< 1%), but we need a proper way to handle it. In such cases, we should fallback to a crude diff i.e. Old file completely on the left (in pink) followed by new file completely on the right (green).

**Comment by nickponvert** [comment]
Bumping this, as it just affected me as well. Awesome product!

**Comment by amit1rrr** [comment]
This is now deployed. So in rare cases where we can't compute actual diff , we fall back to simple diff with before and after view. 

cc: @nickponvert @suzil

**Comment by suzil** [comment]
Thanks so much!
