### ISSUE TITLE
Ability to turn off bot comments on PR

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#22]
There can be following cases where users would like to turn off bot comments,

- Too many bot comments. User's have consolidated ReviewNB link into one of their own bots. E.g. https://github.com/tensorflow/docs/pull/491

We should provide repository level settings where users can opt out of bot comments. 

_Please upvote/downvote the issue indicating whether you think this is useful enhancement or not_

**Comment by lamberta** [comment]
Hi Amit, any progress on this?

**Comment by amit1rrr** [comment]
Hey Billy,
I haven't had anyone else request or show interest in this so couldn't prioritize it. What I can do right now for you is to turn off bot comments for tensorflow/docs repository since you have merged the PR link and it already has lots of bots posting to it. If more people request this, we can make a standard UI to turn this feature on/off. What do you think?

**Comment by lamberta** [comment]
That sounds good to me. Thanks, Amit!

**Comment by amit1rrr** [comment]
Change is deployed. There won't be any comments on tensorflow/docs from ReviewNB bot. Let me know if you see any problems.
