### ISSUE TITLE
30-file limit?

### ISSUE THREAD

**Issue by gsganden** [ReviewNB/support#24]
I'm reviewing a PR with 41 file changes (mostly just files being moved because we are reorganizing), but I only see 30 files on ReviewNB. Is there a 30-file per-PR limit for ReviewNB? If so, is it possible to remove that limit?

**Comment by amit1rrr** [comment]
Somebody just reported this as well. I will take a look. Sorry for the inconvenience.

**Comment by amit1rrr** [comment]
There was indeed a file limit getting applied in some cases. I have fixed the issue, now you should be able to see all the files. Let me know if you face any issues.
