### ISSUE TITLE
Support Zeppelin notebooks

### ISSUE THREAD

**Issue by cmenguy** [ReviewNB/support#30]
Zeppelin notebooks have similar structure (JSON) even if the fields are laid out a bit differently. It would be very useful to support Zeppelin notebooks with ReviewNB, we use a mixture of Jupyter and Zeppelin for different tasks, and being able to use ReviewNB as the one-stop place for all things notebook would be very appealing.

Technically I think the following needs to be considered:
* Extension for Zeppelin notebooks is JSON, and there's probably lots of JSON files in Github that are not notebooks. At the same time relying on the notebooks all being called `note.json` is very fragile and we actually name notebooks differently in Github. So for discovery I think you would either need to parse each JSON file and see if the structure matches Zeppelin structure, or require that users save their Zeppelin notebooks with a specific extension like .zepl or something like that (I've actually seen people do that)
* The structure of the JSON file is fairly well documented, I remember being able to write a parser for Zeppelin files fairly easily, so it sounds like this could be easy to add.
* And because Github only supports rendering .ipynb files natively, it could be interesting to add in ReviewNB a way to also convert the Zeppelin notebook to a Jupyter one with the ability to add that automatically in the PR. I can share some code for that if needed.

**Comment by amit1rrr** [comment]
Thanks @cmenguy for starting this discussion. I see two feature requests in there,

1. Support diff and commenting for Zepellin notebooks
2. Automatically convert all Zepellin notebooks into Jupyter for easy browsing/rendering on GitHub UI

I can see these both being useful for Zepellin users. Given you're the first person requesting it lets put this issue for gathering interest for some time. That will tell us the demand for it and help us triangulate better on the problem itself. 

**Anyone interested in Zepellin support on ReviewNB please upvote here.**

**Comment by amit1rrr** [comment]
We haven't had enough interest in Zepellin notebooks. Closing.
