### ISSUE TITLE
visual diff not rendering cell-level changes

### ISSUE THREAD

**Issue by lukeorland** [ReviewNB/support#33]
We have a notebook in a private repo where the visual diff in ReviewNB shows all the cells as newly added cells at the top, followed by all the same cells in their previous state as removed cells.

Inspected the diff of this notebook, and the added and removed lines are interspersed. I.e., the diff doesn't start with a block of `+` lines followed by `-` lines, as the visual diff is showing.

Have you seen this before, and is there a change we should avoid making to the notebook that causes the visual diff to render this way?

One clue is that several of the cells have `cell_type` changes in the diff:

``` diff
-   "cell_type": "markdown",
+   "cell_type": "code",

...

-   "cell_type": "code",
-   "execution_count": 5,
+   "cell_type": "raw",
```

**Comment by amit1rrr** [comment]
@lukeorland Thanks for reporting. 

> all the cells as newly added cells at the top, followed by all the same cells in their previous state as removed cells.

This is a [fallback to simple diff](https://github.com/ReviewNB/support/issues/21) when we can't actually predict the changes from the patch. It happens rarely and I've seen this typically happen for very large diffs.

I would be happy to take a look and see what's happening in this specific case. If you think it's OK for me to look at this diff for debugging purposes then send me the commit/PR url to amit@reviewnb.com

**Comment by lukeorland** [comment]
Thanks for the response. 

> I would be happy to take a look and see what's happening in this specific case. If you think it's OK for me to look at this diff for debugging purposes then send me the commit/PR url to amit@reviewnb.com

I'll have to check with my team.
