### ISSUE TITLE
Latex is not rendered in markdown cells

### ISSUE THREAD

**Issue by suzil** [ReviewNB/support#36]
ReviewNB rendering:
![Screenshot_2019-07-10 https app reviewnb com](https://user-images.githubusercontent.com/13723264/60980266-7189e480-a334-11e9-92ca-f25c5770ce39.png)

Local rendering:
![Screenshot_2019-07-10 1_BoW_text_classification](https://user-images.githubusercontent.com/13723264/60980550-f83ec180-a334-11e9-884d-721a39bf3e3f.png)

Eg. https://app.reviewnb.com/scoutbee/pytorch-nlp-notebooks/pull/13/files/

Markdown code:
```
## Model Definition

Layer 1 affine: $$x_1 = W_1 X + b_1$$
Layer 1 activation: $$h_1 = \textrm{Relu}(x_1)$$
Layer 2 affine: $$x_2 = W_2 h_1 + b_2$$
output: $$p = \sigma(x_2)$$
Loss: $$L = −(ylog(p)+(1−y)log(1−p))$$
Gradient: 
$$\frac{\partial }{\partial W_1}L(W_1, b_1, W_2, b_2) = \frac{\partial L}{\partial p}\frac{\partial p}{\partial x_2}\frac{\partial x_2}{\partial h_1}\frac{\partial h_1}{\partial x_1}\frac{\partial x_1}{\partial W_1}$$

Parameter update:
$$W_1 = W_1 - \alpha \frac{\partial L}{\partial W_1}$$
```

**Comment by amit1rrr** [comment]
@suzil Thank you for reporting. I looked at it and seems like there's a MathJax rendering issue when there are multiple displayMath formulas in a single markdown cell and all are highlighted.

I am building a fix for it right now. Should be out in a day or so. I will keep you posted here.

**Comment by amit1rrr** [comment]
@suzil This is now fixed. Please let me know if you see any issues. Thanks again :)

![Screenshot 2019-07-11 at 9 54 45 PM](https://user-images.githubusercontent.com/1350490/61068011-8ba3ef80-a426-11e9-92b2-8e355b6d18b7.png)

**Comment by suzil** [comment]
Amazing!! Thanks for the support.
