### ISSUE TITLE
Expand multiple files in diff

### ISSUE THREAD

**Issue by juhoautio** [ReviewNB/support#37]
Feature request: allow any number of files to remain expanded in the diff.

Additionally there could be buttons to expand or collapse all files in the diff.

Currently it works so that if you click the arrow to expand the diff for a file, any currently expanded file diff is collapsed.

**Comment by amit1rrr** [comment]
> allow any number of files to remain expanded in the diff.

> there could be buttons to expand or collapse all files in the diff.

Thanks @juhoautio. I like both the UI suggestions. I should be able to get them in for your next update. Let's keep this issue open, I will keep you posted here.
