### ISSUE TITLE
Minor rendering issue within markdown code block diff

### ISSUE THREAD

**Issue by cfoisy-osisoft** [ReviewNB/support#40]
Screenshots would be better here. First ReviewNB correctly identify the difference:
![image](https://user-images.githubusercontent.com/25752437/63884252-d3191780-c9a3-11e9-9a71-2a086d303e0c.png)

but from a formatting point of view the difference is within the code block, which is not the case in the visual diff. Here is the original in JupyterLab: 
![image](https://user-images.githubusercontent.com/25752437/63884375-09ef2d80-c9a4-11e9-8333-bcd0dcab5a05.png)

**Comment by amit1rrr** [comment]
@cfoisy-osisoft Thank you for reporting. Looks like we weren't properly handling some cases when there are code block edits in markdown cells. 

The fix is now deployed. Feel free to reopen the issue if you see any problems.
