### ISSUE TITLE
markdown in ReviewNB comments

### ISSUE THREAD

**Issue by lukeorland** [ReviewNB/support#42]
Coming from GitHub, every time I type comments in ReviewNB I find myself typing markdown markup characters like `` ` `` and then deleting them when I remember that ReviewNB doesn't parse the markdown in code review comments.

Is this on the roadmap?

**Comment by amit1rrr** [comment]
@lukeorland Thanks for the feature request. Markdown formatting in comments was not on the roadmap as yet but I've also felt the need for this before. Much easier to quickly do formatting (hyperlinks, bullets, backticks) in markdown than fiddling with the UI buttons. 

I've added this request to our backlog now. It might take some time to get to it but it's on our radar now, so thank you for that.

**Comment by amit1rrr** [comment]
ReviewNB now supports markdown formatting while writing comments. You can type in all common markdown formatting options including hyperlinks, bullets, backticks, bold, italics, headers, quotes etc.

cc: @lukeorland @MarkDaoust
