### ISSUE TITLE
License for the free version

### ISSUE THREAD

**Issue by JanuszL** [ReviewNB/support#44]
Hi,
Could you provide a full license for the free version (I'm mostly interested and do and don'ts)?

**Comment by amit1rrr** [comment]
@JanuszL we do not have license text for hosted offering. As the pricing suggests, you can use the free offering with any open source repository without any restrictions. We serve a lot of open source repositories including those from AWS, GCP, fast.ai, Microsoft etc. 

If you have any specific question around do's / don'ts please let me know.

**Comment by amit1rrr** [comment]
Closing this. Feel free to  reach out on amit@reviewnb.com if you have any follow ups.

**Comment by JanuszL** [comment]
@amit1rrr thank you for the support.
