### ISSUE TITLE
Rendering issue of markdown tables 

### ISSUE THREAD

**Issue by cfoisy-osisoft** [ReviewNB/support#45]
Here are screenshots: 

In JupyterLab everything looks fine:
![image](https://user-images.githubusercontent.com/25752437/70957891-8ab26200-2045-11ea-9f4d-c0869cfc47c1.png)

Now the visual diffs struggles a bit rendering: 
![image](https://user-images.githubusercontent.com/25752437/70957952-b897a680-2045-11ea-8edc-284b28ade2b9.png)

**Comment by amit1rrr** [comment]
@cfoisy-osisoft Thank you for reporting. I dug into the problem and looks like our diff rendering is not handling markdown cell table changes properly. I have deployed a change which fixes part of the problem (table alignment is correct now). There's still some work remaining to fix it fully as I need to figure out a way to highlight the entire table row (and not just a single column).  I will be able to get back to this early next month, I hope the quick fix that we deployed helps you until then.

**Comment by amit1rrr** [comment]
@cfoisy-osisoft Thank you for your patience. Now I've deployed a proper fix to handle markdown table diffs. 

Given how complex it was to handle all cases of table modifications, we've decided to fallback on markdown text diff highlighting as shown in the screenshot below. Markdown text is highly readable so it serves our purpose. 

Feel free to reopen if you see any issues.

<img width="566" alt="Screenshot 2020-01-04 at 1 14 09 PM" src="https://user-images.githubusercontent.com/1350490/71762607-52d96480-2ef7-11ea-9465-41f5dd54632f.png">
