### ISSUE TITLE
Prettier table CSS

### ISSUE THREAD

**Issue by sid-kap** [ReviewNB/support#47]
Jupyter has pretty nice default CSS for tables, for example when printed by Pandas. Would we be able to copy some of this CSS to make rendered tables look nicer?
https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/less/renderedhtml.less

There are some nice example table screenshots in https://github.com/jupyter/notebook/pull/1776

**Comment by amit1rrr** [comment]
@sid-kap  Thanks for reporting and linking to the css. I have picked up the changes and deployed it just now. Tables look much nicer now. See screenshot. You would get this with next month's update for Affirm along with [markdown commenting](https://youtu.be/UUJ3BEd2u7g) & [collapsible diffs](https://raw.githubusercontent.com/ReviewNB/support/master/email-hyperlinks/collapsible_diff.gif).

Cheers!



<img width="536" alt="Screenshot 2020-01-29 at 8 08 44 PM" src="https://user-images.githubusercontent.com/1350490/73366104-6350e500-42d3-11ea-9eef-134ae913480b.png">

**Comment by amit1rrr** [comment]
Reopening for a bit - turns out the negative lookahead I used in the regex is not supported in Firefox & Safari yet. So I had to revert the change. Will deploy a fix in some time.

**Comment by amit1rrr** [comment]
Fixed, resolving!

**Comment by sid-kap** [comment]
Awesome, thanks!!
