### ISSUE TITLE
Some missing plotly cell outputs

### ISSUE THREAD

**Issue by cfoisy-osisoft** [ReviewNB/support#49]
Not sure why (different version of plotly?) but most of our plotly graphs show correctly in the side-by-side diff, while for some we get:
![image](https://user-images.githubusercontent.com/25752437/76024830-c567c000-5ef9-11ea-98fc-3287a2086d95.png)

Source URL: https://app.reviewnb.com/cfoisy-osisoft/academic-hub/pull/7/files/

**Comment by amit1rrr** [comment]
@cfoisy-osisoft Thank you for reporting. There was an issue where plotly graphs wouldn't render when there are multiple outputs. I have pushed a fix & now it should work fine. 

Please let me know if you see any more problems.

**Comment by cfoisy-osisoft** [comment]
@amit1rrr Thanks for the quick fix. Now all plots are showing, but unfortunately many of them have a duplicate shown at a different scale, e.g.:

![image](https://user-images.githubusercontent.com/25752437/76115551-5b612080-5fb6-11ea-9d27-01c98990967a.png)

**Comment by amit1rrr** [comment]
> many of them have a duplicate shown at a different scale

@cfoisy-osisoft Actually these are not  duplicates. One is a PNG image output & the other is plotly's HTML output. You can test it by hovering over the image (nothing happens) and the HTML (you'll see plotly's controls). 

The previous version of the file (left hand side of the diff) has both image & HTML outputs hence they are rendered one after the other.
