### ISSUE TITLE
"Read access to emails" Permission is requested, mistake?

### ISSUE THREAD

**Issue by oribar** [ReviewNB/support#50]
I was about to enlist as a "Lite"-tier customer when I realized that you are requesting this permission as well ("Read access to emails"). I assume that this is a mistake?

![image](https://user-images.githubusercontent.com/40392908/76400596-3b9c7480-6389-11ea-9f9a-9dfd88ec524b.png)

**Comment by amit1rrr** [comment]
@oribar Thanks for reaching out. It's not a mistake, we do request permission to read your email address on GitHub. We use this to send out occasional email about new features, major updates to our service & sometimes tips/tools/techniques to make the most with Jupyter notebooks. User can unsubscribe by clicking "Unsusbscribe" link prominently visible in all our emails.

Hope that helps. Let me know if you have any questions.
