### ISSUE TITLE
Bullet points are not visually aligned correctly 

### ISSUE THREAD

**Issue by rayjtong** [ReviewNB/support#51]
**Issue:** Bullet points are not aligned correctly on ReviewNB on the Commits tab and the Changes tab.
 

**Description:** We have a ipynb in Github with documentation with the '*' symbol for bullet points. When viewed on ReviewNB, the formatting is correct on the DISCUSSION tab. However on the COMMITS and CHANGES tabs, the bullet points are aligned incorrectly and displayed on the following row.

 

**Example:** Blacking out some content, but you can see the code, expected output, and incorrect output examples.

**CODE:**
![Screen Shot 2020-03-10 at 1 38 34 PM](https://user-images.githubusercontent.com/61708915/76447256-bd4acd00-639e-11ea-9588-4eb5d4bc1c51.png)

**EXPECTED OUTPUT (Discussion Tab):**
![Screen Shot 2020-03-10 at 1 41 58 PM](https://user-images.githubusercontent.com/61708915/76447262-c3d94480-639e-11ea-9894-6aec67b3e11d.png)

**DISPLAYED OUTPUT (Commits Tab & Changes Tab):**
![Screen Shot 2020-03-10 at 1 39 11 PM](https://user-images.githubusercontent.com/61708915/76447264-c63b9e80-639e-11ea-8107-d536eea3b040.png)

It seems like the bullet point is being visually displayed on the row immediately following the marked location on some rows.

**Comment by amit1rrr** [comment]
@rayjtong Thank you for reporting the issue & providing all the details with screenshots. It was a styling error on our side & I have just deployed a fix for this. 

Let me know if you see any more issues. Thanks again!
