### ISSUE TITLE
ReviewNB Bot functionality

### ISSUE THREAD

**Issue by merrcury** [ReviewNB/support#53]
I have noticed weird behaviour of ReviewNB Bot, recently.
+ Why does not ReviewNB Bot comment on every PR(including ipynb files)?
+ What's the reason behind it? 

This behaviour can be seen in `tensorflow/gan`. I'm just curious to know. :wink:

**Comment by amit1rrr** [comment]
@merrcury Thank you for opening the issue. Good to know that you care about bot comments and find them useful :)

There are primarily 2 reasons for absent bot comments (both tied to GitHub outages),

1. GitHub not sending us a webhook that the PR is opened.
2. GitHub API is failing to accept bot comments

I looked at `tensorflow/gan` PRs and there's only one PR ([#20](https://github.com/tensorflow/gan/pull/20)) that is missing bot link. I looked into our logs and we never received GitHub webhook for this pull request. Looks like this PR was opened when [this incident was going on at GitHub](https://www.githubstatus.com/incidents/q07bfjh7jf1t). 


There's no easy workaround if GitHub doesn't send us notifications that a pull request is opened. I also assume (and expect) GitHub to resend missed webhooks after recovery. Maybe that is not happening today. If I see more issues like this, I'll talk to the GitHub team about this.

**Comment by merrcury** [comment]
That makes sense. I'll keep an eye about such behaviour in future as well & will report to you if it happens too frequently. Btw, We love ReviewNB.

**Comment by markusbkoch** [comment]
@amit1rrr thanks for the awesome product. I assume the bots don't show up in [this PR](https://github.com/cadCAD-org/cadCAD/pull/148) because it was opened before we gave ReviewNB access to the repo? Is there a way to flag it so that the bot becomes aware of it?

**Comment by amit1rrr** [comment]
@markusbkoch Yes, we start posting bot comments on PRs created after ReviewNB app is installed on the repo. Technically, it is possible to backfill all past PRs but it would generate a lot of email notifications for people watching these repositories who might consider this a spam as most of them might not even know about ReviewNB (considering this is a new installation).


Couple of things to solve your problem though -

1. ReviewNB URL format for PR, commit, repo are all identical to GitHub URL format. That means, if you are on GitHub PR page then just changing the URL from github.com to app.reviewnb.com should take you to corresponding page.
1. You can even [create a dynamic bookmark](https://medium.com/@amitrathi/dynamic-bookmarks-for-reviewnb-52a7db356d4) to quickly jump from GitHub to ReviewNB and vice a versa.
