### ISSUE TITLE
Review comments for Commits

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#55]
Currently ReviewNB only supports discussion/comments on a Pull Request (PR). This is mainly so that entire feedback loop (comments, replies, follow-up changes) are all captured under a single PR.

But sometimes it could be handy to be able to write comments on a commit. That way users can give quick feedback to author without creating a pull request every time.

***
_Feel free to upvote/downvote the issue indicating whether you think this is useful feature or not. I also welcome additional questions/comments/discussion on the issue._

**Comment by tekumara** [comment]
This would be great because it would eliminate the friction that comes with creating a PR. What would also be nice is when viewing the commits you could see which one have comments attached to them.

**Comment by amit1rrr** [comment]
We now have [JDoc](https://blog.reviewnb.com/) which lets you write comments on any notebook file. This lets you use Jupyter notebooks similar to how Google Docs is used for collaboration. Team can have conversation on any notebook cell. 

JDoc eliminates the need to writing comments on a commit & acts as a better container for all the conversation on a given notebook.
