### ISSUE TITLE
How to view any notebook in ReviewNB hosted on GitHub? 

### ISSUE THREAD

**Issue by merrcury** [ReviewNB/support#57]
I want to visualize a notebook in someone's PR and Unfortunately, ReviewNB is not installed there. Is there any feature just like [nbviewer](https://nbviewer.jupyter.org/), where we can see difference of custom commits/Pull Requests?

**Comment by amit1rrr** [comment]
Unfortunately, no. Unless the owner/admin of the repository have permitted access to the repository, it can't be viewed on ReviewNB.

If this is an open source repository, can you not request the admin to install ReviewNB on it? I don't see any reason for them to reject it.
