### ISSUE TITLE
latex rendering of non-markdown text

### ISSUE THREAD

**Issue by neilpeterman** [ReviewNB/support#60]
I noticed some logs that had been printed to stderr that appeared to be rendered in a latex-like way (leading to really funny behavior or text that looked like errors). I think it might be appropriate to treat stderr or text that is printed from cells as plaintext and not try to parse it.

Minimal example that shows rendering:
```py
import sys

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

eprint("'{print $1,$2,$3,$4,$5-1}'")
```

**Comment by amit1rrr** [comment]
@neilpeterman Thanks for reporting. It was indeed looking off :)

I have deployed a fix that escapes $ sign from the plain text output now. Checkout the screenshot below. [Test commit](https://app.reviewnb.com/amit2rrr/PythonDataScienceHandbook/commit/01636ade2c2733a8a7231f5f8016f9c230c6a425/) for reference. 

![Screenshot 2020-05-28 at 1 08 30 PM](https://user-images.githubusercontent.com/1350490/83113272-0f210a80-a0e5-11ea-876f-e59c06711058.png)
