### ISSUE TITLE
Missing space in markdown diff

### ISSUE THREAD

**Issue by cfoisy-osisoft** [ReviewNB/support#61]
Here is an example:
![image](https://user-images.githubusercontent.com/25752437/83777418-63813880-a657-11ea-8dd0-efaf7a2de9a2.png)

The notebook has a space in it unlike shown in the green diff. It's a bit annoying because we have to check the source notebook each time to verify if there is indeed a space missing.

**Comment by amit1rrr** [comment]
@cfoisy-osisoft Thanks for reporting. There was a CSS styling issue that was stopping white spaces from being rendered in some diff highlighting cases. I have deployed a fix and you shouldn't face this problem now. 

Closing. Feel free to reopen if you see any issues. Thank you.
