### ISSUE TITLE
Feature request: disable ReviewNB for gh-pages (and/or specific branches)

### ISSUE THREAD

**Issue by kratsg** [ReviewNB/support#64]
Hi,

Thanks for the tool. We're using it nicely in all of our PRs -- however we use gh-pages for deploying docs, and we're starting to get comments from ReviewNB on commits to gh-pages. It would be great to disable these somehow.

Thanks!

./cc @matthewfeickert

**Comment by amit2rrr** [comment]
@kratsg @matthewfeickert Thank you for reporting the issue. Bot comment on commits is a new feature and we definitely want to reduce any noise. To that effect, we've disabled bot comments on `gh-pages` branch & if the committer has `bot` in it's username (e.g. `github-actions[bot]`).  

This fix is now deployed. Let us know if this doesn't work for you for some reason.

**Comment by matthewfeickert** [comment]
Thanks for the super speedy fix!
