### ISSUE TITLE
Support for BitBucket

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#7]
Extend ReviewNB to be used with BitBucket.

_Feel free to upvote/downvote the issue indicating whether you think this is useful feature or not. I also welcome additional questions/comments/discussion on the issue._

**Comment by amit1rrr** [comment]
API Documentation:

BitBucket Server API: https://developer.atlassian.com/server/bitbucket/reference/rest-api/
BitBucket Cloud API: https://developer.atlassian.com/bitbucket/api/2/reference

**Comment by dohertyfjatl** [comment]
Bitbucket Server 6.7 will include a new "patch" API, which can be used to retrieve a raw patch for a pull request or commit. Please see the following issue https://jira.atlassian.com/browse/BSERV-11451 for more details.

Thanks and best regards,
Frank Doherty
Atlassian Bitbucket

**Comment by unknownlighter** [comment]
Since Bitbucket server now supports patch API, is there any ETA for support it in ReviewNB?

**Comment by amit1rrr** [comment]
@unknownlighter Sorry I do not have any ETA for BitBucket support in ReviewNB. I will definitely post it here if & when I have something concrete on this front.

**Comment by merrcury** [comment]
Hey Amit, Is there any update on bitbucket integration?

**Comment by amit1rrr** [comment]
We did an API compatibility test for Bitbucket integration & couple of things were unclear (or were not supported) in Atlassian Bitbucket. We've opened following issues ~3 weeks ago on their community forum to get some clarity,

- [Can we specify webhook endpoints for OAuth apps?](https://community.atlassian.com/t5/Bitbucket-questions/Can-we-specify-webhook-endpoint-for-OAuth-apps/qaq-p/1590078#M60932)
- [Restrict OAuth consumer to select repositories](https://community.atlassian.com/t5/Bitbucket-questions/Restrict-OAuth-consumer-to-selected-repositories/qaq-p/1590058)

No response yet. Please upvote or ask your BitBucket sales/support team for some attention. 

cc: @unknownlighter maybe you can help us :)

**Comment by merrcury** [comment]
Let's indulge Atlassian on Twitter.

**Comment by epyu-lee** [comment]
https://jira.atlassian.com/browse/BCLOUD-21601

**Comment by amit1rrr** [comment]
Hello Everyone,
Good news! Bitbucket integration for [ReviewNB](https://www.reviewnb.com/) is now live! 

You can review rich diffs for Jupyter notebooks & collaborate via notebook pull requests. It's currently in free public beta, you can sign up directly from[ our website](https://www.reviewnb.com/).

If you find Bitbucket integration useful, please [spread the word](https://ctt.ac/aOfbb).

**Comment by amit1rrr** [comment]
Please note, ReviewNB currently only supports Bitbucket Cloud repositories. 

If you're looking for Bitbucket Server or Data Center support, please [fill this form](https://forms.gle/z7vpLynnn4sJgbS56) & we'll reach out to you when ready.
