### ISSUE TITLE
SMTPAuthenticationError: Must issue a STARTTLS command first

### ISSUE THREAD

**Issue by omartrigui** [ReviewNB/support#71]
**Description**:

I was inspecting the logs of ReviewNB and i noticed the following stacktrace:
```
Logging into SMTP Server for Authentication!
Traceback (most recent call last):
  File "/app/org/utility/onprem_util.py", line 106, in verify_smtp_auth
    smtp.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)
  File "/usr/local/lib/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/local/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (530, b'Must issue a STARTTLS command first')
```

For the record, I have triggered a test email via `/send_test_email` endpoint and it works fine. According to ReviewNB [documentation](https://docs.reviewnb.com/self-hosting/docker.html), EMAIL_PORT defaults to port 587 which is the port that uses StartTLS most often.

Regarding this stacktrace, what would you advise ? Thanks !

**Additional context**:

- My setup is configured with [Amazon Simple Email Service](https://aws.amazon.com/ses/)
- reviewnb version: v0.2.15
- SMTP server port: 587

**Comment by amit1rrr** [comment]
@omartrigui We are just logging this error so it's available in case we need to debug something. If `/send_test_email ` is successfully sending a test email for you then no need to worry about this error message.

Closing. Feel free to reopen if you see any issues. Also - feel free to write to us at support@reviewnb.com if you face any issues in self hosted installation.

**Comment by omartrigui** [comment]
@amit1rrr Thanks for your reply. Out of curiosity and after checking the documentation, I wonder if there is an admin panel or preview that provides some insights from the existing content ? For an additional context, I noticed the existence of `is_staff` field in ReviewNB database.

**Comment by amit1rrr** [comment]
Admin / super user concept isn't there in the app yet (some of those tables/fields are created by the framework). Most things are pretty straightforward in the DB itself. If you ever need anything that's not intuitive, just write to support@reviewnb.com and we'll help you with a query. It's not ideal but it's what it is for now :)
