### ISSUE TITLE
Recent fork does not show up under https://app.reviewnb.com/

### ISSUE THREAD

**Issue by Daniel-Mietchen** [ReviewNB/support#72]
I am new to ReviewNB and wanted to give it a try for reviewing some notebooks in a repo for which I do not have commit rights. This seemed not possible (please let me know if it is, and how), so I forked the repo under my primary account. 

That was a few seconds after I had registered for ReviewNB, and now, about 15 min later, my new fork of that repo still does not show up under https://app.reviewnb.com/ . 

I did not see a way to re-trigger the indexing of the repos to include the new fork, and I do not want to fork it again into another account, so I'm currently stuck and would appreciate pointers.

**Comment by Daniel-Mietchen** [comment]
As a workaround, I chose the option "only select repositories", where the new fork could be selected.

**Comment by amit1rrr** [comment]
> I am new to ReviewNB and wanted to give it a try for reviewing some notebooks in a repo for which I do not have commit rights. This seemed not possible (please let me know if it is, and how)

That's correct. Repo admin needs to install ReviewNB on their own repository for us to have access to it. That is the permission model of GitHub. You can request the repository's admin/owner to install ReviewNB on their repo.

> That was a few seconds after I had registered for ReviewNB, and now, about 15 min later, my new fork of that repo still does not show up under https://app.reviewnb.com/ .

If you've installed ReviewNB on your own account & given access to ReviewNB to this repo then the repository should be instantly available. If this is not happening for you then we'd definitely like to look at it. Let us know the name of the repository and put the permission in "ALL" mode to reproduce the issue. If this is private repo then you might want to just send this info over email to support@reviewnb.com

**Comment by Daniel-Mietchen** [comment]
@amit1rrr The repo in question is https://github.com/Daniel-Mietchen/openVirus and is shown in the image in https://github.com/ReviewNB/support/issues/73 . I just checked ReviewNB again with the "ALL" setting, and it is again not there.

**Comment by amit1rrr** [comment]
So the issue was that we were only showing first 100 repositories per installation & hence openVirus wasn't showing up. We've deployed a fix that should show you all repositories now. Let me know if you still face any issues.
