### ISSUE TITLE
A folder that exists in the repo does not show up in ReviewNB

### ISSUE THREAD

**Issue by Daniel-Mietchen** [ReviewNB/support#73]
After the workaround from https://github.com/ReviewNB/support/issues/72#issuecomment-703309994 , I am stuck again, since the "jupyter" folder included in the [repo that I want to review](https://github.com/Daniel-Mietchen/openVirus) does not show up in my ReviewNB list of the repo's content:
![Screenshot_2020-10-04 https app reviewnb com](https://user-images.githubusercontent.com/465923/95026271-3329c500-065e-11eb-9823-032f895c59e5.png)
![Screenshot_2020-10-04 Daniel-Mietchen openVirus](https://user-images.githubusercontent.com/465923/95026274-345af200-065e-11eb-9955-3ec166cae3ba.png)

Aagain, any pointers would be appreciated.

**Comment by amit1rrr** [comment]
We were using GitHub API which fetches 100,000 files/directory listing (or upto 7 MB of data whichever comes earlier). This repository has files over this limit and hence some folders/files were not being shown. 

We've deployed a fix that fetches each subdirectory separately in case we hit the API limits. You should be able to see all folders now. Let me know if you still face any issues.
