### ISSUE TITLE
What flavour of Markdown is supported?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [ReviewNB/support#74]
The text fields say "markdown supported", but their behaviour for things like ```highlighting``` or [linking](https://github.com/ReviewNB/support/issues/74) is different from the Markdown dialects I am used to, so I would appreciate a bit of documentation as to which flavour it is and how to use it.

**Comment by amit1rrr** [comment]
It's a GitHub flavoured markdown spec although it might not fully support all the option that GitHub does.

> their behaviour for things like highlighting or linking is different from the Markdown dialects I am used to

Both highlighting & linking is the same as that of writing comments on GitHub. Backticks are used for highlight and square bracket followed by rounded bracket are used for hyperlinks. You might find this [guide](https://github.github.com/gfm/) useful.
