### ISSUE TITLE
Notebook review app

### ISSUE THREAD

**Issue by bruhanov** [ReviewNB/support#77]
We want to buy a notebook review app from the marketplace.
But organizations that pay via purchase order or invoice instead of credit card can't use the Marketplace to add non-GitHub integrations. 
We contacted Github support with this question, but they advised to write to you:
"To work around this, please contact the vendor of the integration directly and have them add it to your organization."

We hope for help in this issue.
Thanks in advance.

Organization: CJSC BIOCAD

Sincerely, Pavel

**Comment by amit1rrr** [comment]
Hello Pavel,
Yes, it's a limitation of GitHub wherein their invoiced customers can't yet purchase marketplace apps. In such cases, we can setup your subscription directly with us. Please write to support@reviewnb.com with the following information and we'll be happy to setup your account -

- Legal name & address of your company
- Name/URL of your GitHub org?
- Which [plan](https://www.reviewnb.com/#pricing) would you like to use?
