### ISSUE TITLE
Notebooks appear one under each other, instead of side by side [Bug]

### ISSUE THREAD

**Issue by ShahaRaz** [ReviewNB/support#79]
I'd like to compare 2 versions of a notebook (2 following commits in Github).
But the notebooks appear one under each other, instead of side by side

![image](https://user-images.githubusercontent.com/55464049/104120876-e5021d00-5342-11eb-8ea4-c36eb81a8d3a.png)

**Comment by amit1rrr** [comment]
Can you please share the commit or PR URL where you're seeing this? If this is a private repository, you can also write in to support@reviewnb.com

**Comment by ShahaRaz** [comment]
Sure, this is the commit 

https://github.com/ShahaRaz/ML_House_Prices_Preds2021A/commit/3db07427306a461be04b440f64a05a51678514db

**Comment by amit1rrr** [comment]
@ShahaRaz We looked into this. Our diff falls back to [simple before-after view](https://github.com/ReviewNB/support/issues/21) in rare cases when the git patch is so large that our algorithm can't compute the exact edits that might have happened in the commit. It's more prone to simple diff if you use non-standard editors like Colab, nteract etc. 

Looks like both the above things happened in this commit (30k lines changed & Colab editor) so our algorithm couldn't really compute line-by-line diff. Sorry for the experience but there's not much we can do about this at the moment. If possible, we'd recommend you to stick to a single notebook editor (preferably JupyterLab) & keep the size of edit at a manageable level.
