### ISSUE TITLE
Get faster to a diff view

### ISSUE THREAD

**Issue by katrinleinweber** [ReviewNB/support#8]
Hello and thank you for this app! Finally a good solution to [this problem](https://youtu.be/1e26rp6qPbA?t=1861) :-) The diff view is really good!

I tried it just now for one repo in a GitHub Organisation that I'm part and wanted to share my main impression: too many clicks to get to that really good diff.

Please consider to add some kind of "auto-opening" behaviour on each level:

- https://app.reviewnb.com/ => open repo if there is only a single one
- in the commit/PR overview of the repo => hide/grey-out those without a `.ipynb` & open the latest one
- in the file list of a commit => open the `.ipynb` automatically.

Right now, each of these steps requires a user-interaction, which I feel is caused by the single-column layout.

Please consider adding a sidebar, which (on each of the above-listed levels) lists the other available items. I'm hoping that this would enable a main panel to auto-open a sensibly selected diff (like latest or last viewed) without giving the impression of stumbling down a rabbit hole uncontrollably. I'm picturing a [macOS-Finder-like layout](https://duckduckgo.com/?q=macos+finder+colums&ia=images&iax=images) ;-)

What do you think?

PS: I realise that this issue may contain several feature requests. Please let me know if you'd rather split it into more detailled, individual issues.

**Comment by amit1rrr** [comment]
@katrinleinweber Thank you for the feature request.

I understand that it can be too many clicks to get to the diff. I have taken your feedback and a few more conversations I had earlier and created this [issue](https://github.com/ReviewNB/support/issues/9). 

I expect the most usage for ReviewNB PR diff and commenting would originate from the GitHub PR page. So having a link handy in there would speed up the workflow. In future, I might create a browser plugin that does the same for commits as well.

**Comment by katrinleinweber** [comment]
Cool :-)
