### ISSUE TITLE
Free Tier but still able to see private repository notebooks

### ISSUE THREAD

**Issue by amichuda** [ReviewNB/support#81]
Hi,

I just signed up for the free, Open Source/Educational Tier and I can see the notebooks in my private repository. Is this part of some free trial or have I accidentally committed to paying for it?

**Comment by amit1rrr** [comment]
Yes, we offer certain amount of grace views of private repositories for new users on the Free plan. The goal is to help new users explore the functionality without being obstructed with a paywall.
