### ISSUE TITLE
Diff view dosn't allow commenting

### ISSUE THREAD

**Issue by javadevghosh** [ReviewNB/support#82]
![image](https://user-images.githubusercontent.com/13223648/105930280-3d514400-5ffe-11eb-827f-1255416811e5.png)
There's no option for commenting. However, [documentation](https://uploads-ssl.webflow.com/5ba4ebe021cb91ae35dbf88c/5c7d0095d99ee508018a9878_Screenshot%202019-03-04%20at%204.08.48%20PM.png) ,states that users can comment on Diff.

**Comment by amit1rrr** [comment]
Commenting is available on the Pull Request diff (and directly on the notebook file) but not on the Commit diff. I believe the screenshot you shared is of a commit diff. 

Closing. Feel free to reopen if you there are any follow up questions. Thanks!
