### ISSUE TITLE
local diffs

### ISSUE THREAD

**Issue by TejasAvinashShetty** [ReviewNB/support#83]
Can one have an installable local version of reviewnb?
It would enable one to view notebook diffs locally before committing.
This would be like sublime merge but for notebooks instead of code files.

**Comment by amit1rrr** [comment]
Hello @TejasAvinashShetty 
We don't have local version of ReviewNB that works on pre-commit diffs. I'd recommend using [nbdime](https://github.com/jupyter/nbdime) &/or [jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git) extension both of which which would give you local diffs.

Hope that helps.  Feel free to reopen if you've any follow up questions.
