### ISSUE TITLE
first colum no content

### ISSUE THREAD

**Issue by pflegende** [ReviewNB/support#85]
![Err1colNix](https://user-images.githubusercontent.com/52720420/113495099-3dcef500-94ef-11eb-913c-f2a0e9ab9193.JPG)

tested in 

browser Opera
Version:75.0.3969.149
Betriebssystem:Windows 7 32-bit

browser firefox
87.0 (64-Bit)

https://app.reviewnb.com/pflegende/cppInterpreter/commit/57fe4121b56a686d3662d2770254df20ea5a89fb/

reffers to Github

https://github.com/pflegende/cppInterpreter

**Comment by amit1rrr** [comment]
@pflegende Thanks for reporting. Looking at the [commit diff on GitHub](https://github.com/pflegende/cppInterpreter/commit/57fe4121b56a686d3662d2770254df20ea5a89fb) it seems like entire notebook json is on a single line. That is not a typical arrangement of a notebook written in Jupyter (or JupyterLab). Are you using a non-Jupyter editor to author these notebooks (e.g. Colab, Nteract etc.)?

**Comment by pflegende** [comment]
the ipynb is a fork from https://github.com/olilarkin/XeusClingMatplotLibExample

and edited after uploaded to binder running in binder environment and edited inside the running jupyterlab

then downloaded local as ipynb file
then uploaded to github 

what you seen inside  
[commit diff on GitHub](https://github.com/pflegende/cppInterpreter/commit/57fe4121b56a686d3662d2770254df20ea5a89fb)

for the moment I don't know where the "single line" behaivor does come from


May be it is something around the binder runtime environment. Because I create all my jupyter files in this matter (over binder or sometimes by cocalc) it will produce allways this "single line" behaivor, I think.

You have some idea or proposal to transform a singel line ipynb file in a right-formatted?

thank you for analysing the behaivor of my try of reviewNB.
Cool tool!

**Comment by pflegende** [comment]
update,

new findings

https://app.reviewnb.com/pflegende/BetteninventurTH/commit/d82cae6ca7062eb686a2040a4aeb77ff63aa8f3a/

tried on other repo with a notebook:
https://github.com/pflegende/BetteninventurTH

the notebook:
https://github.com/pflegende/BetteninventurTH/blob/master/BetteninventurThur-CountCat2ixio.ipynb

it renders all the diffs
(you must scroll down a long way ...)

(is not so usefull because github identifies the whole file as different)
I think this is Github bevaivor. May be the json of ipynb is too big.

CU
:)

**Comment by pflegende** [comment]
yes, the same behaivor with the first reported.
"Downunder", i meannscrolling long way down, is there lso the diff on the left hand side ...

Im sorry!
was my fault!

**Comment by amit1rrr** [comment]
> You have some idea or proposal to transform a singel line ipynb file in a right-formatted?

I'd first check where/how this file is getting into single line JSON format in your workflow. In most cases, this happens if you use non-standard editors (Colab, Cocalc etc.).

**Comment by pflegende** [comment]
... thank you for helping hands!
Will try it out.
:)
