### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by tkphd** [ReviewNB/support#87]
In a GitHub notebook review, ReviewNB says

> You're receiving email notifications because you particiapted in the conversation.

Please run spellcheck across the codebase. [Codespell](https://github.com/codespell-project/codespell) may be useful for this & CI.

**Comment by amit1rrr** [comment]
@tkphd Thanks for reporting this. The typo is now fixed. 

Codespell looks neat, we're giving it a shot as well. Thank you :)
