### ISSUE TITLE
Collapsible headers and Table of Contents

### ISSUE THREAD

**Issue by s-kyy** [ReviewNB/support#89]
Hi! I've been working with the nbextensions with Jupyter Notebooks and I'm very reliant on the feature of being able to collapse headers and quickly navigating through code using a floating table of contents to the right/ left of the page. Would this be possible in ReviewNB?

**Comment by amit1rrr** [comment]
That's definitely an interesting idea. I'm assuming you're talking about [ToC2](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html) and [collapsible headings](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/collapsible_headings/readme.html). Please correct me if I'm wrong.

Table of contents looks really handy to quickly navigate to different parts of the notebook. How well does it work if there's no hierarchy in our headers?

Collapsible headings seems like we need to collapse one at a time which doesn't sound very useful on the surface. How & what do you use this for?

**Comment by s-kyy** [comment]
Hi @amit1rrr. Yes I was mostly referring to the `ToC2` extension for both navigating and collapsing headers. 

I rely on hierarchy a lot in my notebooks, so if the markdown doesn't allow that in ReviewNB, then my notes will look more cluttered on this platform, but not non-navigable if there's at least a table of contents on the side. If you do intend to implement it perhaps allowing for auto-numbering the headers would be nice, but not required. 

The extension remembers which headers are collapsed upon saving the notebook, so when you open the notebook in a new session, only those headers that were opened in the previous session would remain open. This makes it quick to go back to what I was working on. As for viewing on ReviewNb, each commit saves which headers are opened or closed within the notebook, making it easier to scroll to what was being last worked on at the time of the commit, while also having the ability to open the headers if needed. 

The current work around is not viewing the entire notebook, but instead only reviewing the changes. Although it makes sense to me (since I remember where I edited something), collaborators may want to know where this code is in the context of the entire notebook. The table of contents would help with that.

**Comment by amit1rrr** [comment]
>> The current work around is not viewing the entire notebook, but instead only reviewing the changes. Although it makes sense to me (since I remember where I edited something), collaborators may want to know where this code is in the context of the entire notebook.


When you open any commit or PR on ReviewNB we only show the changed cells(and one cell above & below for context). Users can expand more context cells if they need. Given that we only show changed cells initially (and not the entire notebook) the utility of Table of Contents is limited for commit & PR pages. 

Table of Contents might be useful for our [JDoc feature](https://blog.reviewnb.com/commenting-for-jupyter/) where we show entire notebooks on initial load itself. So we'll keep this request in mind for JDoc. Meanwhile, we'll also asses how popular is `ToC2` in our user base and see if it makes sense to build a tighter integration such as reading the collapsed state from notebook etc.
