### ISSUE TITLE
Directly link to ReviewNB PR from GitHub PR

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/support#9]
If user has to jump from GitHub PR page to the corresponding page in ReviewNB there are some non-standard ways,

1. Replace github.com with app.reviewnb.com as the URL structure is exactly the same.
2. Create a following bookmarklet (which just automates the step 1 above):
`javascript:(function(){ window.open(window.location.toString().replace(/.*github\.com\/(.*pull\/\d*).*/, 'https://app.reviewnb.com/\$1')); })() 
`

While these are nice, there is no standard way to jump from GitHub PR page to corresponding page in ReviewNB. This feature request is to create such a bridge. 

Simplest way is to listen to the PR created webhook, check if newly created PR contains any Notebook changes and post a bot comment if PR has any Notebooks. Something simple like Netlify bot comment below would do,

<img width="390" alt="netlify" src="https://user-images.githubusercontent.com/1350490/52767775-7aaaaa00-3051-11e9-99cd-31842eb11610.png">

**Comment by amit1rrr** [comment]
This is now live. Every time you open a PR that has any Notebook modifications, our bot posts a  ReviewNB link to the PR conversation.

E.g. https://github.com/tensorflow/docs/pull/382

<img width="784" alt="Screenshot 2019-03-11 at 2 13 49 PM" src="https://user-images.githubusercontent.com/1350490/54110865-80a16a00-4408-11e9-9eba-3a9cd16e9d49.png">

**Comment by lamberta** [comment]
Nice. Thanks!

**Comment by katrinleinweber** [comment]
Nice indeed! 1k thanks for this feature :-)
