### ISSUE TITLE
Unable to remove repositories.

### ISSUE THREAD

**Issue by paulsendavidjay** [ReviewNB/support#91]
I click on +/- repositories, select the group I want to edit, and see a the page listing the four repos I have associated. 
I can click on the repos and view contents, but there is no way to remove them. If I click on the +/- button at the bottom, I'm just brought back to the first page.

**Comment by amit1rrr** [comment]
@paulsendavidjay When you click on `+/- REPOSITORY` the app should take you to this GitHub page (you can click following link to go there directly as well): https://github.com/apps/review-notebook-app/installations/new

From there you should be able add or remove repositories for this installation. Please make sure that you're logged into your GitHub account (this is required to make any installation changes on GitHub).

Let us know if this resolves the issue for you.

**Comment by amit1rrr** [comment]
Closing. Feel free to reopen if this is still an issue.
