### ISSUE TITLE
Integration ReviewNB with notebooks comming from Databricks

### ISSUE THREAD

**Issue by anguitart** [ReviewNB/support#96]
When a notebook is commit to github via the link with Databricks, ReviewNB is not able to detect it as the same notebook, instead it is marked as a new one and it difficults the revision.

Is there a plan to solve this issue? I would like to have some comment on this to decide next steps in our organization.

**Comment by amit1rrr** [comment]
@anguitart You opened the same issue here a few hours ago - https://github.com/ReviewNB/support/issues/95

Please see our response on that issue. Please feel free to continue the discussion there. Closing this one as a duplicate.
