### ISSUE TITLE
Plotly outputs stop rendering after a comment is made

### ISSUE THREAD

**Issue by zachary-jablons-okcupid** [ReviewNB/support#99]
Hey there,

Trying out some of the features here and noticed that while earlier plotly issues were resolved, when I comment on a cell with a plotly output it appears to cause that cell to be blanked out once the review is submitted (but not while it's pending)

Before:
![image](https://user-images.githubusercontent.com/72406994/130127951-10b83e39-cb5d-4ebd-8324-aa2768be5d48.png)

Pending:

![image](https://user-images.githubusercontent.com/72406994/130128075-38320a3b-9a01-43bc-8d22-3d1cd8f43898.png)

After finishing the review (which forces a reload):

![image](https://user-images.githubusercontent.com/72406994/130128179-0fb821f8-5b4d-482d-a907-86351b66f2d0.png)

Resolving the conversation does not restore the output displayed. Is this a known issue? If so, are there any workarounds?

Thanks,
Zach

**Comment by amit1rrr** [comment]
@zachary-jablons-okcupid Thank you for reporting the issue along with screenshots. There was indeed a problem when plotly plot would not render after posting a comment on it. 

We've fixed this issue and the plot should render properly now. Please let us know if you see any issues.

Thanks again for reporting!

**Comment by zachary-jablons-okcupid** [comment]
Thanks for the quick fix! It looks like it all works now
